# Generated by Django 6.0.4 on 2026-07-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('it', 'IT / Software'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('design', 'Design'), ('customer_support', 'Customer Support'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, help_text='e.g. Fresher, 2-4 years, 5+ years', max_length=100),
        ),
    ]
