# Generated by Django 6.0.4 on 2026-07-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='education',
            field=models.CharField(blank=True, help_text='e.g. B.Tech in Computer Science, XYZ University', max_length=300),
        ),
    ]
