# Generated by Django 6.0.4 on 2026-07-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_jobseekerprofile_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
