# Generated by Django 6.0.4 on 2026-07-20 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_rename_name_company_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='owner',
            new_name='user',
        ),
    ]
